DROP TABLE IF EXISTS note;

CREATE TABLE note(
  id SERIAL PRIMARY KEY,
  message TEXT,
  is_deleted INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);